apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: {{ .Values.Replicas }}
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  imagePullPolicy: Never
                  image: library/nginx:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
        - port: 8080
          targetPort: 8080
