name: Deploy Service
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy Nginx
    steps:
    - name: Infrastructure Setup
      uses: medyagh/setup-minikube@master
    - name: Fetch Files
      uses: actions/checkout@v2
    - name: Prepare Manifest
      run:  cat deployment.yaml    
    - name: Apply
      run: |
        kubectl apply -f deployment.yaml       
    - name: Wait for Steady State Check
      run: |
        minikube service list
        kubectl describe deployment.apps/nginx
