name: Deploy Service
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    name: Deploy Nginx
    steps:
    - name: Service Setup
      run: |
        echo "Service Name: Nginx"
        echo "Artifact Tag: Latest"
    - name: Infrastructure Setup
      uses: medyagh/setup-minikube@master
    - name: Fetch Files
      uses: actions/checkout@v2
    - name: Prepare Manifest
      run: |
        go run render_template.go deployment.yaml values.yaml > rendered_deployment.yaml   
    - name: Apply
      run: |
        kubectl apply -f rendered_deployment.yaml       
    - name: Wait for Steady State Check
      run: |
        minikube service list
        kubectl describe deployment.apps/nginx
