name: Deploy Service
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    name: Deploy Nginx
    steps:
    - name: Service Setup
      run: |
        echo "Service Name: $SERVICE_NAME"
        echo "Artifact Tag: $ARTIFACT_TAG"
    - name: Dynamic Provisioned Infrastructure - K8s Cluster
      uses: medyagh/setup-minikube@master
    - name: Dynamic Provision Infrastructure - Create Namespace
      run: |
        kubectl create namespace develop
    - name: Fetch Files
      uses: actions/checkout@v2
    - name: Prepare Manifest
      run: |
        echo "Similuate the go template and rendered manifest"
        cat deployment.yaml
        cat values.yaml
    - name: Dry Run
      run: |
        kubectl apply -f deployment.yaml --dry-run
    - name: Apply
      run: |
        kubectl apply -f deployment.yaml -n develop  
    - name: Wait for Steady State Check
      run: |
        minikube service list -n develop
        kubectl describe deployment.apps/nginx -n develop
    - name: Kubernetes Delete
      run: |
        kubectl delete namespace develop
