name: Deploy Service
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    name: Deploy Nginx
    steps:
    - name: Service Setup
      run: |
        echo "Service Name: Nginx"
        echo "Artifact Tag: Latest"
    - name: Dynamic Provisioned Infrastructure - K8s Cluster
      uses: medyagh/setup-minikube@master
    - name: Fetch Files
      uses: actions/checkout@v2
    - name: Prepare Manifest
      run: |
        echo "Similuate the go template and rendered manifest"
        cat deployment.yaml
        cat values.yaml
    - name: Apply
      run: |
        kubectl apply -f deployment.yaml       
    - name: Wait for Steady State Check
      run: |
        minikube service list
        kubectl describe deployment.apps/nginx
